server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - name: FilterCustom
      routes:
        - id: catalog #identificador de la ruta
          uri: lb://catalog-service #URL donde se hará el redirect segun el predicado definido
          predicates: #Reglas de analisis de request
            - Path=/catalog/** #path de url de request a considerar
        - id: movies
          uri: lb://movie-service
          predicates:
            - Path=/movies/**              

info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka
  management:
    endpoint:
      gateway:
        enabled: true
    endpoints: 
      web:
        exposure:
          include: gateway
