server:
  port: ${PORT:0}

idRandom: ${random.value}

spring:
  application:
    name: catalog-service
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: testCatalog
      port: 27018
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  zipkin:
    beseUrl: htt://localhost:9411/
    enabled: true

queue:
  movie:
    name: movieQueue
  serie:
    name: serieQueue


# Configuracion previa de la base de datos
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password: sa
#  jpa:
#    open-in-view: false
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#        format_sql: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-console


message: hello from catalog-service

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    port: ${server.port}
    instance: ${spring.application.instance_id:${random.value}}
        
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
